services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html/web
      - ./config:/var/www/html/config
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    working_dir: /var/www/html
    env_file: .env
    depends_on:
      - db

  webserver:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress

  db:
    image: mariadb:11.5
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: wp_mailhog
    ports:
      - "8025:8025" # Interface web
      - "1025:1025" # Port SMTP

volumes:
  db_data:
