server {
  listen 80;
  server_name localhost;

  root /var/www/html/web;
  index index.php;

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  location / {
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ ^/wp/(.*\.php)$ {
    include fastcgi_params;
    fastcgi_pass wordpress:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root/wp/$1;
  }

  location ~ ^/(wp-(admin|content|includes)) {
    rewrite ^/(wp-(admin|content|includes))(/.*)$ /wp/$1$3 break;
  }

  location ~ ^/wp-login\.php {
    rewrite ^/wp-login\.php$ /wp/wp-login.php break;
  }

  location ~ \.php$ {
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_pass wordpress:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    expires max;
    access_log off;
    log_not_found off;
  }
}
